[package]
name = "cargo-valgrind"
version = "1.3.0"
authors = ["Julian Frimmel <julian.frimmel@gmail.com>"]
edition = "2018"
description = "A cargo subcommand for running valgrind"
repository = "https://github.com/jfrimmel/cargo-valgrind"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = [
    "cargo",
    "subcomand",
    "cargo-subcommand",
    "valgrind",
    "cli",
]
categories = [
    "development-tools",
    "development-tools::cargo-plugins",
]
exclude = [
    "CHANGELOG.md",
    "tests",
]

[[bin]]
name = "cargo-valgrind"
path = "src/bin/main.rs"

[dependencies.clap]
version = "~2.33"
features = ["wrap_help"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0"

[dependencies.serde-xml-rs]
version = "0.3.1"
default-features = false

[dependencies.colored]
version = "1.8.0"

[dependencies.bytesize]
version = "1.0.0"
