[package]
name = "cargo-valgrind"
version = "0.2.1"
authors = ["Julian Frimmel <julian.frimmel@gmail.com>"]
edition = "2018"
description = "A cargo subcommand for running valgrind"
repository = "https://github.com/jfrimmel/cargo-valgrind"
readme = "README.md"
keywords = [
    "cargo",
    "subcomand",
    "cargo-subcommand",
    "valgrind",
    "cli",
]
categories = [
    "development-tools",
    "development-tools::cargo-plugins",
]

[[bin]]
name = "cargo-valgrind"
path = "src/bin/main.rs"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0"
